name: Maven Package

on:
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Publish to GitHub Packages Apache Maven
      run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
      env:
          GITHUB_TOKEN: ${{ secrets.ATOM_BERG }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.Atomberg }}
          with:
          args: >
            -Dsonar.organization=iot-testing 
            -Dsonar.projectKey=AppiumTest
           
